products/urls.py
from django.urls import path
from products.views import (
    CategoriesListTemplate,
    ProductListView,
    ProductDetaileView,
    CategoryDetaileTemplate,
    ContactTemplate
)

app_name = "products"
urlpatterns = [
    path("", ProductListView.as_view(), name="products"),
    path("product/<int:pk>/", ProductDetaileView.as_view(), name="product"),
    path("category/<int:pk>/", CategoryDetaileTemplate.as_view(), name="category"),
    path("categories/", CategoriesListTemplate.as_view(), name="categories"),
    path('contact/', ContactTemplate.as_view(), name='contact')

]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products.views import HomeTemplate

urlpatterns = [
    path("admin/", admin.site.urls),
    path("products/", include("products.urls", namespace="products")),
    path('', HomeTemplate.as_view(), name='home'),
    path('users/', include('users.urls', namespace='users'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import user_login, logout, user_register, user_profile


app_name = 'users'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('register/', user_register, name='register'),
    path('logout/', logout, name='logout'),
    path('profile/',user_profile, name='profile')
]

products/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    PRODUCT_TYPES = [
        ("bouquet", "Букет"),
        ("sweet", "Сладость"),
        ("toy", "Игрушка"),
        ("greeting_card", "Открытка"),
        ("combo", "Комбо"),
    ]

    name = models.CharField(max_length=64)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to="products_images", blank=True, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="products"
    )
    product_type = models.CharField(max_length=32, choices=PRODUCT_TYPES)

    def __str__(self):
        return f"{self.name} ({self.get_product_type_display()})"

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    




class Packaging(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = "Оформление"
        verbose_name_plural = "Оформление"

    def __str__(self):
        return self.name


# Дополнительные свойства для букетов
class Bouquet(models.Model):
    product = models.OneToOneField(
        Product, on_delete=models.CASCADE, related_name="bouquets"
    )
    description = models.TextField(blank=True, null=True)
    packaging = models.ForeignKey(
        Packaging, on_delete=models.CASCADE, related_name="bouquets"
    )

    class Meta:
        verbose_name = "Букет"
        verbose_name_plural = "Букеты"

    def __str__(self):
        return self.product.name


class BouquetOption(models.Model):
    bouquet = models.ForeignKey(
        Bouquet, related_name="options", on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.bouquet.product.name} - {self.quantity} шт."


# Дополнительные свойства для сладостей
class Sweet(models.Model):
    product = models.OneToOneField(
        Product, on_delete=models.CASCADE, related_name="sweets"
    )
    description = models.TextField(blank=True, null=True)
    quantity = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        verbose_name = "Сладость"
        verbose_name_plural = "Сладости"

    def __str__(self):
        return f"{self.product.name} - {self.quantity} шт."

    # Метод который отображают все сладости
    @staticmethod
    def get_list_sweets():
        return Sweet.objects.select_related("product").all()


class Toy(models.Model):
    product = models.OneToOneField(
        Product, on_delete=models.CASCADE, related_name="toys"
    )

    class Meta:
        verbose_name = "Игрушка"
        verbose_name_plural = "Игрушки"

    def __str__(self):
        return self.product.name

    # Метод который отображают все игрушки
    @staticmethod
    def get_list_toys():
        return Toy.objects.select_related("product").all()


class GreetingCard(models.Model):
    product = models.OneToOneField(
        Product, on_delete=models.CASCADE, related_name="cards"
    )
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = "Открытка"
        verbose_name_plural = "Открытки"

    def __str__(self):
        return self.product.name

    # Метод который отображают все открытки
    @staticmethod
    def get_list_cards():
        return GreetingCard.objects.select_related("product").all()
    


class Combo(models.Model):
    product = models.OneToOneField(
        Product, on_delete=models.CASCADE, related_name="combos"
    )
    bouquet = models.ForeignKey(
        Bouquet, on_delete=models.CASCADE, related_name="combos"
    )
    sweet = models.ForeignKey(Sweet, on_delete=models.CASCADE, related_name="combos")
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = "Комбо"
        verbose_name_plural = "Комбо"

    def __str__(self):
        return f"{self.product.name} - {self.bouquet.product.name} - {self.sweet.product.name} "

products/views.py
from decimal import Decimal
from django.shortcuts import render
from django.views.generic import ListView, TemplateView, DetailView
from django.shortcuts import render, get_object_or_404, redirect
from .models import Bouquet, BouquetOption
from products.models import Category, Product, Bouquet, Sweet, Toy, Combo, GreetingCard


class ProductListView(ListView):
    model = Product
    template_name = "products/products.html"
    context_object_name = "products"


class ProductDetaileView(DetailView):
    model = Product
    template_name = "products/product.html"
    context_object_name = "product"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()

        related_name = {
            'bouquet': 'bouquets',
            'sweet': 'sweets',
            'toy': 'toys',
            'greeting_card': 'cards',
            'combo': 'combos'
        }
        related_attr = related_name.get(product.product_type)
        context[product.product_type] = product.product_type = getattr(product, related_attr, None)
        context.update({
            "list_sweets": Sweet.get_list_sweets(),
            "list_cards": GreetingCard.get_list_cards(),
            "list_toys": Toy.get_list_toys()
        })

        return context


class CategoriesListTemplate(ListView):
    model = Category
    template_name = "products/categories.html"
    context_object_name = "categories"


class CategoryDetaileTemplate(DetailView):
    model = Category
    template_name = "products/category.html"
    context_object_name = "category"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.get_object()  # Получаем текущую категорию
        context["products"] = Product.objects.filter(
            category=category
        )  # Фильтруем продукты по категории
        return context


class HomeTemplate(TemplateView):
    template_name = "products/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["bouquets"] = Bouquet.objects.all()

        return context



class ContactTemplate(TemplateView):
    template_name = 'products/contact.html'

products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Магазин{% endblock %}</title>
    {% block css %}
    {% endblock %}
</head>
<body>
    <header>
        <h1>🌹 Цветочный Магазин 🌷</h1>
    </header>
    <div class='top-menu'>
        <ul>
            <a href="{% url 'home' %}">Главная страница</a>
            <a href="{% url 'products:contact' %}">Контакты</a>
            <a href="#">Меню</a>
            <a href="#">Корзина</a>
            {% if user.is_authenticated %}
                <a href="{% url 'users:profile' %}">Профиль</a>
                {% if user.is_superuser or user.is_staff %}
                    <a href="{% url 'admin:index' %}">Админ-панель</a>
                {% endif %}
                <a href="{% url 'users:logout' %}">Выход</a>

            {% else %}
                <li>
                    <a href="{% url 'users:login' %}">Войти</a>
                    <a href="{% url 'users:register' %}">Регистрация</a>
                </li>
            {% endif %}
        </ul>
    </div>

    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p>&copy; 2024 Магазин. Все права защищены.</p> 
    </footer>
</body>
</html>

products/templates/products/categories.html
{% extends 'products/base.html' %}

{% block content %}
<nav class='categories'>
    {% if show_categories %}
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'products:category' category.id %}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
</nav>

<h2>Все категории</h2>
<div>
    {% for category in categories %}
        <div>{{ category.name }}</div>
    {% endfor %}
</div>

{% endblock %}

products/templates/products/category.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
<nav class='categories'>
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'products:category' category.id %}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
</nav>

<h1>Каталог {{ category.name }}</h1>
<p>{{ category.description }}</p>

{% for product in products %}
<div class="product-card">
    {% if product.image %}
        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-image" width="200">
    {% else %}
        <img src="{% static 'default-image.jpg' %}" alt="{{ product.name }}" class="product-image" width="200">
    {% endif %}
    <div class="product-info">
        <h2 class="product-name">{{ product.name }}</h2>
        <p class="product-price">Цена: {{ product.price }} тенге.</p>
        <p><a href="{% url 'products:product' product.id %}">Подробнее</a></p>
    </div>
</div>
{% endfor %}

{% endblock %}

products/templates/products/contact.html
{% extends "products/base.html" %}

{% block title %} Контакт {% endblock %}
{% block content %}
<div>
    <h3>НАШИ КОНТАКТЫ:</h3>
    <p>По любым вопросам вы можете связаться с нами любым удобным для вас способом. Мы всегда рады обратной связи от наших клиентов касательно качества цветов или работы наших сотрудников.</p>
    <p>ИНФОРМАЦИЯ О МАГАЗИНАХ:</p>
    <p>г. Астана, пр. Мангилик Ел, 36</p>
    <p> ул. Санжара Асфендиярова, 2</p>
    <p> Время работы: круглосуточно</p>
</div>
{% endblock %}

products/templates/products/home.html
{% extends 'products/base.html' %}

{% block content %}

<nav class='categories'>
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'products:category' category.id %}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
</nav>

<div>
    <h3>Круглосуточная доставка цветов в Астане</h3>
</div>



{% endblock %}

products/templates/products/product.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
  {% if bouquet %}

    <div class="product-detail-container">
      <div class="product-image-section">
        {% if bouquet.product.image %}
          <div class="product-image-main">
            <img src="{{ bouquet.product.image.url }}" alt="{{ product.name }}" class="product-main-image" width="100%" />
          </div>
        {% endif %}
      </div>
      

      <div class="product-info-section">
        <h1 class="product-name">{{ bouquet.product.name }}</h1>
        <p class="product-price">
          <span>{{ bouquet.product.price }}</span> тенге
        </p>

        <div class="product-options">
          <label for="add-card">Добавить открытку:</label>
          <select id="add-card" name="add_balloons">
            <option value="no">Не выбрано</option>
            {% for card in list_cards %}
              <option value="{{ card.id }}">{{ card.product.name }} - {{ card.product.price }} тенге</option>
            {% endfor %}
          </select>

          <label for="add-toy">Добавить мягкую игрушку:</label>
          <select id="add-toy" name="add_toy">
            <option value="no">Не выбрано</option>
            {% for toy in list_toys %}
              <option value="{{ toy.id }}">{{ toy.product.name }} - {{ toy.product.price }} тенге</option>
            {% endfor %}
          </select>

          <label for="add-sweets">Добавить сладости:</label>
          <select id="add-sweets" name="add_sweets">
            <option value="no">Не выбрано</option>
            {% for sweet in list_sweets %}
              <option value="{{ sweet.id }}">{{ sweet.product.name }}({{ sweet.quantity }})шт - {{ sweet.product.price }} тенге</option>
            {% endfor %}
          </select>
        </div>

        <button class="add-to-cart-btn">Добавить в корзину и купить</button>

        <ul class="product-details">
          <p class="product-description">{{ bouquet.description }}</p>
        </ul>

        <p class="product-note">Для вашего удобства перед отправкой и при получении букета предоставляется ФОТО-ОТЧЕТ.</p>
      </div>
    </div>
    {% elif combo %}
    <div class="product-detail-container">
      <!-- Секция изображения -->
      <div class="product-image-section">
        {% if combo.product.image %}
          <div class="product-image-main">
            <img src="{{ combo.product.image.url }}" alt="{{ combo.name }}" class="product-main-image" />
          </div>
          {% comment %} <div class="combo-image-thumbnails">
            <!-- Миниатюры изображений -->
            <img src="{{ combo.image.url }}" alt="{{ combo.name }}" class="combo-thumbnail" />
            <img src="{{ combo.image.url }}" alt="{{ combo.name }}" class="combo-thumbnail" />
          </div> {% endcomment %}
        {% endif %}
      </div>

      <!-- Секция информации -->
      <div class="product-info-section">
        <h1 class="product-name">{{ combo.product.name }}</h1>
        <p class="product-price">
          <span>{{ combo.product.price }}</span> тенге
        </p>

        <div class="product-options">
          <label for="add-cards">Добавить открытку:</label>
          <select id="add-cards" name="add_balloons">
            <option value="no">Не выбрано</option>
            {% for card in list_cards %}
              <option value="{{ card.id }}">{{ card.product.name }} - {{ card.product.price }} тенге</option>
            {% endfor %}
          </select>

          <label for="add-toy">Добавить мягкую игрушку:</label>
          <select id="add-toy" name="add_toy">
            <option value="no">Не выбрано</option>
            {% for toy in list_toys %}
              <option value="{{ toy.id }}">{{ toy.product.name }} - {{ toy.product.price }} тенге</option>
            {% endfor %}
          </select>

          <label for="add-sweets">Добавить сладости:</label>
          <select id="add-sweets" name="add_sweets">
            <option value="no">Не выбрано</option>
            {% for sweet in list_sweets %}
              <option value="{{ sweet.id }}">{{ sweet.product.name }}({{ sweet.quantity }})шт - {{ sweet.product.price }} тенге</option>
            {% endfor %}
          </select>
        </div>

        {% comment %} <p class="product-composition">Состав букета: {{ combo.bouquet.get_flowers_names }}</p> {% endcomment %}
        <p class="product-description">{{ combo.description }}</p>

        <button class="add-to-cart-btn">Добавить в корзину и купить</button>
      </div>
    </div>

  {% elif toy %}
    <div class="product-detail-container">
      <!-- Секция изображения -->
      <div class="product-image-section">
        {% if toy.product.image %}
          <div class="product-image-main">
            <img src="{{ toy.product.image.url }}" alt="{{ toy.name }}" class="product-main-image" />
          </div>
        {% endif %}
      </div>

      <!-- Секция информации -->
      <div class="product-info-section">
        <h1 class="product-name">{{ toy.product.name }}</h1>
        <p class="product-price">
          <span>{{ toy.product.price }}</span> тенге
        </p>

        <div class="product-options">
          <div class="add-card-section">
            <label for="add-card">Добавить открытку:</label>
            <select id="add-card" name="add_balloons">
              <option value="no">Не выбрано</option>
              {% for card in list_cards %}
                <option value="{{ card.id }}">{{ card.product.name }} - {{ card.product.price }} тенге</option>
              {% endfor %}
            </select>
          </div>
        </div>
        

        <!-- Кнопка добавления в корзину -->
        <div class="product-actions">
          <button class="add-to-cart-btn">Добавить в корзину</button>
        </div>
      </div>
    </div>

  {% elif greeting_card %}
    <div class="product-detail-container">
      <!-- Секция изображения -->
      <div class="product-image-section">
        {% if greeting_card.product.image %} 
          <div class="product-image-main">
            <img src="{{ greeting_card.product.image.url }}" alt="{{ greeting_card.name }}" class="product-main-image" />
          </div>
          {% comment %} <div class="card-image-thumbnails">
            <!-- Миниатюры изображений -->
            <img src="{{ card.image.url }}" alt="{{ card.name }}" class="card-thumbnail" />
            <img src="{{ card.image.url }}" alt="{{ card.name }}" class="card-thumbnail" />
          </div> {% endcomment %}
        {% endif %} 
      </div>

      <!-- Секция информации -->
      <div class="product-info-section">
        <h1 class="product-name">{{ greeting_card.product.name }}</h1>
        <p class="product-price">
          <span>{{ greeting_card.product.price }}</span> тенге
        </p>

        <div class="product-options">
          <label for="add-note">Добавить записку:</label>
          <select id="add-note" name="add_note">
            <option value="no">Не выбрано</option>
            <option value="yes">Да</option>
          </select>
        </div>

      <p class="card-description">{{ greeting_card.description }}</p> 

        <button class="add-to-cart-btn">Добавить в корзину и купить</button>
      </div>
    </div>

  {% elif sweet %}
    <div class="product-detail-container">
      <!-- Секция изображения -->
      <div class="product-image-section">
        {% if sweet.product.image %}
          <div class="product-image-main">
            <img src="{{ sweet.product.image.url }}" alt="{{ sweet.name }}" class="product-main-image" />
          </div>
        {% endif %}
      </div>

      <!-- Секция информации -->
      <div class="product-info-section">
        <h1 class="product-name">{{ sweet.product.name }}</h1>
        <p class="product-price">
          <span>{{ sweet.product.price }}</span> тенге
        </p>
        <p class="product-description">{{ sweet.description }}</p>

        <!-- Кнопка добавления в корзину -->
        <div class="product-actions">
          <button class="add-to-cart-btn">Добавить в корзину</button>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

products/templates/products/products.html
{% extends 'products/base.html' %}

{% block content %}
  <div class="product-list">
    <h1>Список товаров</h1>
    <div class="product-cards">
      {% for product in products %}
        <div class="product-card">
          <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-image" />
          <h3 class="product-name">{{ product.name }}</h3>
          <p class="product-description">{{ product.description }}</p>
          <p class="product-price">{{ product.price }} ₽</p>
          <a href="{% url 'products:product' product.id %}" class="btn btn-primary">Подробнее</a>
        </div>
      {% endfor %}
      
    </div>
  </div>
{% endblock %}